<a href="https://colab.research.google.com/github/brucenelsonm88/Hamoye/blob/main/Stage_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

In [12]:
file_path = "/content/drive/MyDrive/Dataset/FoodBalanceSheets_E_Africa_NOFLAG.csv"

In [14]:
!pip install chardet

Requirement already satisfied: chardet in /usr/local/lib/python3.10/dist-packages (5.2.0)

In [15]:
import chardet

In [16]:
with open(file_path, 'rb') as f:
    encoding = chardet.detect(f.read())['encoding']

In [17]:
df = pd.read_csv(file_path, encoding=encoding)

In [18]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [19]:
df.shape

(60943, 12)

In [28]:
df['Y2014'].isnull().sum()/60943 *100

2.6073544131401474

In [29]:
# Select columns 'Y2017' and 'Area'
selected_columns = df[['Y2017', 'Area']]

# Perform groupby operation on 'Area' and sum the values in 'Y2017' for each area
grouped_data = selected_columns.groupby('Area').sum()

# Find the area with the highest sum in 2017
area_with_highest_sum = grouped_data.idxmax()[0]  # Get the index of the maximum sum

print("Area with the highest sum in 2017:", area_with_highest_sum)

Area with the highest sum in 2017: Nigeria

In [32]:
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [34]:
df.columns

Index(['Area Code', 'Area', 'Item Code', 'Item', 'Element Code', 'Element',
       'Unit', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018'],
      dtype='object')

In [35]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [42]:
# Filter the DataFrame for Madagascar and select the 'Y2015' column
madagascar_y2015 = df[df['Area'] == 'Madagascar']['Y2015']

# Sum the 'Y2015' column to get the total Protein supply quantity in Madagascar in 2015
total_protein_supply = madagascar_y2015.sum()

print("Total Protein supply quantity in Madagascar in 2015:", total_protein_supply)

Total Protein supply quantity in Madagascar in 2015: 126674.9

In [44]:
# Calculate the correlation between 'Element Code' and each year's data
correlations = {}
for column in df.columns:
    if column.startswith('Y'):  # Assuming year columns start with 'Y'
        correlation = df['Element Code'].corr(df[column])
        correlations[column] = correlation

# Find the year with the least correlation with 'Element Code'
least_correlated_year = min(correlations, key=correlations.get)

print("Year with the least correlation with 'Element Code':", least_correlated_year)

Year with the least correlation with 'Element Code': Y2016

In [46]:
# Select columns 'Y2017' and 'Area'
selected_columns = df[['Y2017', 'Area']]

# Perform groupby operation on 'Area' and sum the values in 'Y2017' for each area
grouped_data = selected_columns.groupby('Area').sum()

# Sort the grouped data by the sum of 2017 values in ascending order
sorted_grouped_data = grouped_data.sort_values(by='Y2017')

# Get the area with the 7th lowest sum in 2017
seventh_lowest_area = sorted_grouped_data.index[6]  # Indexing starts from 0

print("Area with the 7th lowest sum in 2017:", seventh_lowest_area)

Area with the 7th lowest sum in 2017: Guinea-Bissau

In [47]:
# Filter the DataFrame for the 'Processing' element and select the 'Y2017' column
processing_2017 = df[df['Element'] == 'Processing']['Y2017']

# Calculate the total sum of 'Processing' in 2017
total_processing_2017 = processing_2017.sum()

print("Total sum of Processing in 2017:", total_processing_2017)

Total sum of Processing in 2017: 292836.0

In [50]:
# Filter the data for the years 2015 and 2018
df_filtered = df[['Item', 'Y2015', 'Y2018']]

# Perform a groupby operation on the 'Item' column and sum the values
grouped_data = df_filtered.groupby('Item')[['Y2015', 'Y2018']].sum()

# Get the total sum of Wine produced in 2015 and 2018 respectively
wine_2015_sum = grouped_data.loc['Wine', 'Y2015']
wine_2018_sum = grouped_data.loc['Wine', 'Y2018']

print("Total sum of Wine produced in 2015:", wine_2015_sum)
print("Total sum of Wine produced in 2018:", wine_2018_sum)

Total sum of Wine produced in 2015: 4251.81
Total sum of Wine produced in 2018: 4039.32